### ISSUE TITLE
More effective drawing apply_latency when osd number is counted in hundreds

### ISSUE THREAD

**Issue by Kallio** [grinapo/collectd-ceph#16]
When selecting just like max  5  osd:s and aliasing it by node, we can make grafana drawing faster and readable.  
`aliasByNode(highestMax(storage.cloud.collectd.ceph-ceph-osd-*.gauge-apply_latency_ms, 3), 5)`

**Comment by grinapo** [comment]
I have no objection against new dashboards, they don't use any relevant amount of disk space. Your pull is welcome. :-)

**Comment by y4ns0l0** [comment]
See #18

**Comment by grinapo** [comment]
Thanks, merged. (You have changed a few names here and there, just mentioning; as an example it'll work just fine.)
