### ISSUE TITLE
Cluster I/O Latency metrics are not gathered 

### ISSUE THREAD

**Issue by tstrulw** [grinapo/collectd-ceph#20]
Hi,
Thank you very much for keeping this project alive.
Im using this y4ns0l0 dockerized solution to monitor my cluster.
I still have problems with Cluster I/O Latency
I see "no datapoints" error.and while looking in graphite i can see that the relevant metrics are not gathered.
Cluster I/O latency: cluster.gauge.latency
What seems to be the problem? Thank you very much!

**Comment by y4ns0l0** [comment]
Hi,
Yes I/O latency gathering is a little bit tricky to setup. By default, a pool named "test" must exist on your cluster or the name of the pool must be specified in the variable `CEPH_TEST_POOL` when you start your docker.

Please send your `docker logs`, if you still have the problem.

**Comment by tstrulw** [comment]
Hi, 
I used rbd pool as test pool (we dont use it we use volumes and vms pools for openstack)
from the logs i can see:
"ceph-latency: failed to run rados bench :: Command 'timeout 30s rados --cluster 9da15133-d4c8-4b52-8fe4-40f112414325 -p rbd bench 10 write -t 1 -b 65536' returned non-zero exit status 1"

When I try the command manually i get "no monitors specified to connect to.
couldn't connect to cluster! error -2"

**Comment by y4ns0l0** [comment]
I suppose you've done an error while starting the docker container :
`-e CEPH_CLUSTER_NAME=<my ceph cluster>` should correspond to the name of the ceph config file in `/etc/ceph` inside your container.

Try `-e CEPH_CLUSTER_NAME=ceph` and let me know...

**Comment by tstrulw** [comment]
Works great! Thank you :)

**Comment by y4ns0l0** [comment]
You're welcome ! Can you close this issue please.
