### ISSUE TITLE
Per OSD and PG information is not gathered (Luminous)

### ISSUE THREAD

**Issue by tstrul1** [grinapo/collectd-ceph#22]
Hi,
Im using @y4ns0l0 dockerized solution to monitor my cluster.

I cant see metrics like osd-* or pg.
It used to work before....
I can see only: cluster, mon, osd, pool, pool-*
pg   and osd-* are missig....
when i run docker logs i see:

> ceph: failed to get stats :: 'fs_perf_stat' :: Traceback (most recent call last):
>   File "/usr/lib/collectd/plugins/ceph/base.py", line 162, in read_callback
>     stats = self.get_stats()
>   File "/usr/lib/collectd/plugins/ceph/ceph_pg_plugin.py", line 70, in get_stats
>     data[ceph_cluster][osd_id]['apply_latency_ms'] = osd['fs_perf_stat']['apply_latency_ms']
> KeyError: 'fs_perf_stat'
> 
> Unhandled python exception in read callback: UnboundLocalError: local variable 'stats' referenced before assignment
> read-function of plugin `python.ceph_pg_plugin' failed. Will suspend it for 15360.000 seconds.

> ceph: failed to get stats :: 'fs_perf_stat' :: Traceback (most recent call last):
>   File "/usr/lib/collectd/plugins/ceph/base.py", line 162, in read_callback
>     stats = self.get_stats()
>   File "/usr/lib/collectd/plugins/ceph/ceph_pg_plugin.py", line 70, in get_stats
>     data[ceph_cluster][osd_id]['apply_latency_ms'] = osd['fs_perf_stat']['apply_latency_ms']
> KeyError: 'fs_perf_stat'
> 
> Unhandled python exception in read callback: UnboundLocalError: local variable 'stats' referenced before assignment
> read-function of plugin `python.ceph_pg_plugin' failed. Will suspend it for 7680.000 seconds.

Am i doing something wrong or it is something with luminous? 
When I tried this solution before it worked perfectly.
Thank you

**Comment by y4ns0l0** [comment]
Hi @tstrul1,

Thanks for reporting this bug 👍 
Unfortunately, the collectd plugin is not yet working with Ceph luminous....

But my ceph clusters will be upgraded to luminous soon....

**Comment by tstrul1** [comment]
Thanks a lot
Actually I saw there is a fix that was merged in this commit:
https://github.com/grinapo/collectd-ceph/commit/c4fba6c302d884a3ac43258250654d61ac2890e7

So I just built another docker again. until its get officially fixed :)

**Comment by grinapo** [comment]
did 84ca65168977d1ee6cd260ae4e40b9599831e226 finally fixed it?
