### ISSUE TITLE
Unable to get below metrics using this plugin on my mon node

### ISSUE THREAD

**Issue by vishalbhosale04** [grinapo/collectd-ceph#23]
I am unable to get below metrics in my graphite after using this collectd plugin.

=================================================================
pg_plugin

-rw-r--r-- 1 _graphite _graphite 751720 Sep 18 15:00 gauge-stale.wsp
-rw-r--r-- 1 _graphite _graphite 751720 Sep 18 15:00 gauge-peering.wsp
-rw-r--r-- 1 _graphite _graphite 751720 Sep 18 15:00 gauge-degraded.wsp
-rw-r--r-- 1 _graphite _graphite 751720 Sep 18 15:00 gauge-undersized.wsp
-rw-r--r-- 1 _graphite _graphite 751720 Sep 18 15:00 gauge-remapped.wsp
-rw-r--r-- 1 _graphite _graphite 751720 Sep 18 15:27 gauge-snaptrim_wait.wsp

=================================================================
cluster

-rw-r--r-- 1 _graphite _graphite 751720 Nov 15 03:50 gauge-health_warn.wsp
-rw-r--r-- 1 _graphite _graphite 751720 Nov 15 03:50 gauge-health.wsp
-rw-r--r-- 1 _graphite _graphite 751720 Nov 15 03:50 gauge-health_err.wsp
-rw-r--r-- 1 _graphite _graphite 751720 Nov 15 03:50 gauge-health_ok.wsp

**Comment by grinapo** [comment]
Coming back to this issue I still cannot quite understand how is this related to the repo. 
As a general suggestion you should check collectd logs for errors.
Closing. If it's still relevant please re-open and add more informations.
