### ISSUE TITLE
ceph-latency fails with UnboundLocalError: local variable 'stats' referenced before assignment

### ISSUE THREAD

**Issue by kkplein** [grinapo/collectd-ceph#7]
Hi, first: thanks for creating this fork!

We're running the plugins on debian jessie, python 2.7. All plugins work, except the ceph-latency plugin fails with the following errors:

ceph: failed to get stats :: list index out of range :: Traceback (most recent call last):
                                       File "/usr/lib/collectd/plugins/ceph/base.py", line 162, in read_callback
                                         stats = self.get_stats()...
Nov 01 17:13:55 ceph2 collectd[40152]: Unhandled python exception in read callback: UnboundLocalError: local variable 'stats' referenced before assignment

I have already edited the pool-name from 'data' to a pool that we actually have, plus I downloaded https://github.com/collectd/collectd/blob/collectd-5.4/contrib/python/getsigchld.py (since jessie comes with collectd 5.4) to /usr/local/lib/python2.7/site-packages

Both did not help: same error, still.

Anyone with a suggestion?

**Comment by grinapo** [comment]
The latency plugin is a weird animal: it does that call to 'rados bench' and tries to (more or less blindly) parse the results. When I was fighting with it to work the result was often what you see: the latency plugin `get_stats` got unexpected output from rados, misparsed it, then upper levels choked on it.

My guess is that `rados` utility have changed its output, which gets fouled up in ceph_latency_plugin.py:63. However I tend to remember _someone who have patched that part_, but it was mixed up in various incompatible changes, so I haven't included it. I try to find it...

**Comment by grinapo** [comment]
It is not entirely impossible that now it would work for you, I have merged a much prettier parser for latency. Please try.

**Comment by kkplein** [comment]
Yes! It runs much better! Thanks!
